# Generated by Django 5.1.4 on 2026-01-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='subcategory_images/'),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
