# Generated by Django 5.1.4 on 2026-01-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicecategory_image_servicecategory_service_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_id',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
