# Generated by Django 5.1.4 on 2026-01-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicecategory_deleted_at_servicerequest_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_id',
            field=models.CharField(default='TEMP', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
