# Generated by Django 5.1.4 on 2026-02-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicerequest_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
