# Generated by Django 5.1.4 on 2026-02-06 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_servicecategory_order_servicesubcategory_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequestMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="service_media/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[("image", "Image"), ("audio", "Audio")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="services.servicerequest",
                    ),
                ),
            ],
        ),
    ]
