# Generated by Django 5.2.7 on 2026-03-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_servicerequestmedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
