# Generated by Django 5.1.4 on 2026-01-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('priority', models.IntegerField(choices=[(1, 'Admin'), (2, 'Semi Admin'), (3, 'staff'), (4, 'user'), (5, 'All')], default=1)),
            ],
        ),
    ]
